### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by josephm1** [joshuef/beaker#23]
Operation System: Windows 8 64-bit
Beaker Version:v0.4.3-3
When executing set-up will get error:"[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'redux-node-logger'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Program Files\safe-browser\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at C:\Program Files\safe-browser\resources\app\background-process.build.js:9:40
    at Object.<anonymous> (C:\Program Files\safe-browser\resources\app\background-process.build.js:2028:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

[OK]"

And can't access safe beaker browser on 0.4.3, but could on v0.4.2

**Comment by frabrunelle** [comment]
I also get this error on macOS 10.12.1 with SAFE Browser v0.4.3-2 and v0.4.3-3.

**Comment by josephm1** [comment]
Fixed on v0.4.3-7.
